FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

# safer install (fix ETIMEDOUT / dependency issues)
RUN npm install --no-audit --no-fund --legacy-peer-deps

COPY . .

RUN npm run build


FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx-frontend.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]